### ISSUE TITLE
Unable to activate jekyll-asset-pipeline-0.1.6

### ISSUE THREAD

**Issue by ArneGockeln** [matthodan/jekyll-asset-pipeline#47]
Hello,

I was following the getting started tutorial until step 5. When I try to run jekyll with option "s" or "b" I am getting the following error:

``` bash
Webchef:webchef arnegockeln$ jekyll s
Configuration file: /Users/arnegockeln/Sourcecode/htdocs/static/webchef/_config.yml
/Library/Ruby/Site/2.0.0/rubygems/specification.rb:2112:in `raise_if_conflicts': Unable to activate jekyll-asset-pipeline-0.1.6, because jekyll-3.0.1 conflicts with jekyll (~> 0.12), liquid-3.0.6 conflicts with liquid (~> 2.4) (Gem::ConflictError)
    from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:1280:in `activate'
    from /Library/Ruby/Site/2.0.0/rubygems.rb:198:in `rescue in try_activate'
    from /Library/Ruby/Site/2.0.0/rubygems.rb:195:in `try_activate'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:39:in `require'
    from /Users/arnegockeln/Sourcecode/htdocs/static/webchef/_plugins/jekyll_asset_pipeline.rb:1:in `<top (required)>'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:121:in `require'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:121:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:75:in `block (2 levels) in require_plugin_files'
    from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:74:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:74:in `block in require_plugin_files'
    from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:73:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:73:in `require_plugin_files'
    from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:18:in `conscientious_require'
    from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.1/lib/jekyll/site.rb:97:in `setup'
    from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.1/lib/jekyll/site.rb:49:in `initialize'
    from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:30:in `new'
    from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:30:in `process'
    from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.1/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
    from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
    from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
    from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
    from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
    from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.1/bin/jekyll:17:in `<top (required)>'
    from /usr/bin/jekyll:23:in `load'
    from /usr/bin/jekyll:23:in `<main>'
```

Is there a fix for the current jekyll version 3.0.1?

Best,
Arne

**Comment by guayom** [comment]
I have the same issue

**Comment by janosrusiczki** [comment]
If this is still relevant, I have just updated [my fork](https://github.com/janosrusiczki/japr) with support for the latest Jekyll.

**Comment by janosrusiczki** [comment]
My fork is now merged here so it should be OK.
